"""
Django settings for projeto project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w+dyxc(4!gjae#a*_c#cfpd!#=q$$)+#6p^#u)dqqwr$84v+fl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    'gestaoEventos',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projeto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static", 
]

STATIC_ROOT = BASE_DIR / 'staticfiles'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Configuração do Swagger/Spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # Configuração de Autenticação 
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',  
    ],

    # Configuração de Filtros 
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    
    # Permissões 
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

# Configurações opcionais (Título e descrição da API)
SPECTACULAR_SETTINGS = {
    'TITLE': 'API de Gestão de Eventos',
    'DESCRIPTION': 'API para controle de eventos, atividades e inscrições.',
    'VERSION': '1.0.0',
}

# Permite o api com qualquer pagina html
CORS_ALLOW_ALL_ORIGINS = True

# Sessão expira sempre que fecha a aba
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

JAZZMIN_SETTINGS = {
    "copyright": "IFB e IHWBR",

    "topmenu_links": [
      {"name": "SUPORTE", "url": "https://wa.me/5561999356975?text=Ol%C3%A1%2C%20preciso%20de%20suporte%20para%20o%20sistema%20EventLab.", "new_window": True},
      {"name": "IFB", "url": "https://www.ifb.edu.br/", "new_window": True},
      {"name": "IHWBR", "url": "https://hardware.org.br/", "new_window": True},
    ],

    "show_ui_builder": False,
    
    # Logo a ser usado para o seu site, deve estar presente nos arquivos estáticos
    "site_logo": "img/site_logo.png", 
    
    # Classes CSS aplicadas ao logo
    "site_logo_classes": "img-fluid", # 'img-fluid' é geralmente melhor que 'img-circle' para logos retangulares

    # (Opcional) Logo para a tela de login
    "login_logo": "img/logo.png", 
    "custom_css": "css/custom_admin.css",
    "welcome_sign": "Bem-vindo ao Painel de Admin do EventLab!",

    # Outras configurações que você já tem ou quer adicionar:
    "site_title": "EventLab Admin",
    "site_header": "EventLab",
    # ... (outras configurações)
    #"site_logo_classes": "img-circle",

    "icons": {
        # Ícones para os Modelos específicos (as tabelas)
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users",
        
        # Abas com os nomes conforme seu models.py
        "gestaoEventos.Atividade": "fas fa-list-alt",
        "gestaoEventos.UserEventos": "fas fa-pen",
        "gestaoEventos.Evento": "fas fa-calendar",
        "gestaoEventos.Perfil": "fas fa-user-tag",

        # icone do token
        "authtoken.TokenProxy": "fas fa-key",

    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-gray",
    "accent": "accent-lightblue",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-info",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "journal",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}