# Generated by Django 5.2.8 on 2025-12-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usereventos',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
    ]
